#pragma once

enum ePacketReliability {
    RELIABILITY_UNRELIABLE,
    RELIABILITY_UNRELIABLE_SEQUENCED,
    RELIABILITY_RELIABLE,
    RELIABILITY_RELIABLE_ORDERED,
    RELIABILITY_RELIABLE_SEQUENCED,
    RELIABILITY_UNRELIABLE_WITH_ACK_RECEIPT,
    RELIABILITY_RELIABLE_WITH_ACK_RECEIPT,
    RELIABILITY_RELIABLE_ORDERED_WITH_ACK_RECEIPT,

    RELIABILITY_COUNT
};
